---
- hosts: terraform@10.154.0.5
  tasks:
  - name: Install Java
    yum:
      name: java
      state: latest
    become: true

  - name: Download Jenkins  
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
    become: true

  - name: Shell Jenkins Command
    shell: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    become: true

  - name: Install Jenkins
    yum:
      name: jenkins
      state: latest
    become: true 
...
